name: allure_flutter_test
description: Allure Report adapter for flutter_test and host-run integration_test.
version: 0.1.0
homepage: https://github.com/allure-framework/allure-dart
repository: https://github.com/allure-framework/allure-dart
issue_tracker: https://github.com/allure-framework/allure-dart/issues

environment:
  sdk: ^3.6.0
  flutter: '>=3.24.0'

dependencies:
  allure_dart_commons: ^0.1.0
  allure_dart_test: ^0.1.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dev_dependencies:
  lints: ^5.1.1
